name: 错误报告
description: 模板中的错误反馈
title: "[错误]："
labels: ["error"]
body:
  - type: markdown
    attributes:
      value: 感谢小伙伴的反馈，请填写该表格描述你遇到的错误内容
  - type: dropdown
    id: version
    attributes:
      label: 版本
      description: 请问出现错误的是哪个版本呢？
      options:
        - Miki Stickie.V1
        - Miki Stickie.V2
        - Miki Stickie.V3
        - Miki Stickie.V4
    validations:
      required: true
